### ISSUE TITLE
Create an nzbhydra2 docker image?

### ISSUE THREAD

**Issue by fryfrog** [binhex/arch-nzbhydra#1]
@theotherp has re-written nzbhydra in java and released it as nzbhydra2. They can run in parallel, on different ports which lets it import settings from the old into the new easily. A new docker for it would be great. It'd also let people continue to use the python nzbhydra which is a bit less memory intensive, but slower.

https://github.com/theotherp/nzbhydra2

The poor guy tried to do his own Dockerfile for it, but discovered how... fun Docker can be. :)

And LinuxServer.io is making an attempt at it, but theirs isn't great. I've tried to submit diffs and feedback to them in the past, but it was mostly ignored / rejected so... I haven't bothered again.

**Comment by theotherp** [comment]
@binhex 
If there are any questions please ask.

**Comment by binhex** [comment]
in progress

**Comment by fryfrog** [comment]
Awwwwww yeah. :)
